# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mongoapi/dbtestapp/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/mongoapi/dbtestapp"
    schedule:
      interval: "weekly"
